---
title: "Geographies of Non-Communicable Diseases"
author: "James Millington"
date: '2020-08-05'
output:
  pdf_document:
    toc: yes
  github_document:
    toc: yes
  html_document:
    toc: yes
    df_print: paged
  word_document:
    toc: yes
---


## Aim 

Analyse database of expertise on Non-Communicable Disease (NCDs)

**Questions**

1. Who are the experts in the field?
2. How has expertise changed over time?
3. What are the geographies of expertise?


```{r, echo=F, warning=F, message=F}
#set libraries
library(dplyr)
library(readr)
library(ggplot2)
library(forcats)
library(tmap)
library(mapdata)
library(sf)

#load data
ncd <- read_csv("NCDreports_2021-06-14.csv", col_types = cols(.default = col_character(), Year=col_integer(), PubID=col_integer()))

#load colours
ccolours <- read_csv("gapminder_CC.csv")
col5_vec <- I(ccolours$Colour5)
names(col5_vec) <- ccolours$Country

con6_vec <- I(ccolours$Cont6Colour)
names(con6_vec) <- I(ccolours$Continent6)

top10_vec <- I(ccolours$Top10)
names(top10_vec) <- ccolours$Country

```

## Analysis: Counts

### Authors
```{r, echo=F, warning=F, message=F}

freq_Author <- ncd %>% group_by(Author) %>%
   summarise(count = n()) %>%
   mutate(freq = count / sum(count)) %>%
   arrange(desc(freq))

freq_Author %>%
   filter(count>2) %>%
   ggplot(aes(x=reorder(Author, -count),y=count)) +
   geom_bar(stat="identity") +
   xlab("Author")+
   ggtitle("More than 2 Citations") +
   coord_flip()


ncd %>%
   mutate(Author = fct_lump(Author, n = 10)) %>%
   count(Author) %>%
   top_n(10) %>%
   filter(Author != 'Other') %>%
   ggplot(aes(x=reorder(Author,-n), y=n)) +
   geom_bar(stat="identity") +
   xlab("Author")+
   ylab("Count")+
   ggtitle("Top 10 Authors by Citation")+
   coord_flip()

```

### Countries
```{r, echo=F, warning=F, message=F}

freq_Country <- ncd %>% group_by(Country) %>%
   summarise(count = n()) %>%
   mutate(freq = count / sum(count)) %>%
   arrange(desc(freq))

freq_Country %>%
   filter(count>2) %>%
   ggplot(aes(x=reorder(Country, -count),y=count)) +
   geom_bar(stat="identity") +
   xlab("Country")+
   ggtitle("More than 2 Authors")+
   coord_flip()

topn <- 10

ncd %>%
   mutate(Country = fct_lump(Country, n = topn)) %>%
   count(Country) %>%
   top_n(topn) %>%
   ggplot(aes(x=reorder(Country, -n),y=n)) +
   geom_bar(stat="identity") +
   xlab("Country")+
   ylab("Count")+
   ggtitle(paste0("Top ",topn," Countries by Citation")) +
   coord_flip()

```
Maps (countries) by paper
```{r, echo=F, warning=F, message=F}
#get world data (from maps library) 
data(World)
World <- filter(World, continent != 'Antarctica')

###add barbados (missing in lowres map)
#get barbados from hi res map (can do this for other islands missing in the low res map)
hires <- fortify(map("worldHires", fill=TRUE, plot=FALSE))
barbados <- hires %>% filter(region=="Barbados")

#create multipolygon and set CRS
bst <- sfheaders::sf_multipolygon(
     obj = barbados
     , x = "long"
     , y = "lat"
     , polygon_id = "region"
   ) %>% 
   st_set_crs(4326) %>% 
   st_transform(crs=st_crs(World$geometry)) 

#add barbados to the lowres World data
World <- World %>% add_row(name="Barbados",geometry=bst$geometry)

```


```{r, echo=F, warning=F, message=F}

#with help from https://geocompr.robinlovelace.net/adv-map.html

#get lancet series data only, aggregate authors by year and country
pmap <- ncd %>% 
   group_by(Year, `Lancet Series`, Country) %>%
   summarise(count = n()) %>%
   filter(`Lancet Series` != 'No')

#join NCD data to map data
world.dat <- left_join(World, pmap, b=c('name'='Country'))

#function to plot bubble map for a given year
tmyear <- function(yr){

   pmyear <- tm_shape(world.dat) +
      tm_polygons() +
      tm_shape(filter(world.dat,Year==yr)) +
      tm_bubbles(alpha = 0.75, col = "red", border.col = "black", size = "count") +
      tm_layout(title = paste0(yr))
   
   return(pmyear) 
}

#create plots
pm2005 <- tmyear(2005)
pm2007 <- tmyear(2007)
pm2010 <- tmyear(2010)
pm2013 <- tmyear(2013)
pm2018 <- tmyear(2018)

#plot all years together on a facet map
##need drop.NA.facets=TRUE because there are many NAs in the year column
pmap.facet <-tm_shape(world.dat) +
   tm_polygons() +
   tm_shape(world.dat) +
   tm_bubbles(alpha = 0.75, col = "red", border.col = "black", size = "count") +
   tm_facets(by = "Year", free.coords = FALSE, drop.NA.facets=TRUE)

```


```{r, echo=F, warning=F, message=F}
#print maps
pm2005
pm2007
pm2010
pm2013
pm2018
pmap.facet
```

```{r, echo=F, warning=F, message=F}
#save maps
tmap_save(tm=pm2005, filename="png/map_lancet_2005.png")
tmap_save(tm=pm2007, filename="png/map_lancet_2007.png")
tmap_save(tm=pm2010, filename="png/map_lancet_2010.png")
tmap_save(tm=pm2013, filename="png/map_lancet_2013.png")
tmap_save(tm=pm2018, filename="png/map_lancet_2018.png")
tmap_save(tm=pmap.facet, filename="png/map_lancet_facet.png")
```

```{r, echo=F, warning=F, message=F}
pmap.anim <-tm_shape(world.dat) +
   tm_polygons() +
   tm_shape(world.dat) +
   tm_bubbles(alpha = 0.75, col = "red", border.col = "black", size = "count") +
   tm_facets(along = "Year", free.coords = FALSE, drop.empty.facets = TRUE)

#drop.NA.facets=TRUE produces error. Without that term we get 'missing' in last frame which catched the NA cells in Year column (to avoid this need to have a value in every Year row, so would need every country repeated for every year) 
tmap_animation(pmap.anim, filename = "map_lancet_anim.gif", delay = 75)
```


### Continents
```{r, echo=F, warning=F, message=F}

# freq_Cont <- ncd %>% group_by(Continent) %>%
#    summarise(count = n()) %>%
#    mutate(freq = count / sum(count)) %>%
#    arrange(desc(freq))
# 
# freq_Cont %>%
#    filter(count>2) %>%
#    ggplot(aes(x=reorder(Continent, -count),y=count, fill=Continent)) +
#    geom_bar(stat="identity") +
#    xlab("Continent")+
#    ggtitle("More than 2 Authors")+
#    coord_flip() +
#    scale_fill_manual(values=con6_vec)

ncd %>%
   count(Continent) %>%
   ggplot(aes(x=reorder(Continent, -n),y=n, fill=Continent)) +
   geom_bar(stat="identity") +
   xlab("Continent")+
   ylab("Count")+
   ggtitle("Continents by Citation") +
   coord_flip() +
   scale_fill_manual(values=con6_vec)

```

## Analysis: Temporal

### All Data
```{r, echo=F, warning=F, message=F}

#Publication by year
ncd %>% 
   group_by(Year, `Publication ID`) %>%
   summarise(count = n()) %>%
   ggplot(aes(x=Year)) +
   geom_bar(stat="count", colour="white") +
   ggtitle("Publications by Year") 

#unique author year
ncd %>% 
   group_by(Year, Author) %>%
   summarise(count = n()) %>%
   ggplot(aes(x=Year)) +
   geom_bar(stat="count", colour="white") +
   ggtitle("Unique Authors by Year") 

#all authors by year
ncd %>% 
   ggplot(aes(x=Year)) +
   geom_bar(stat="count", colour="white") +
   ggtitle("Total Authors by Year") 


ncd %>% 
   group_by(Year, Institution) %>%
   summarise(count = n()) %>%
   ggplot(aes(x=Year)) +
   geom_bar(stat="count", colour="white") +
   ggtitle("Unique Institutions by Year") 


ncd %>% 
   group_by(Year, Country) %>%
   summarise(count = n()) %>%
   ggplot(aes(x=Year)) +
   geom_bar(stat="count", colour="white") +
   ggtitle("Unique Countries by Year") 

```


### Top 8 Authors
```{r, echo=F, warning=F, message=F}

topn <- 8

top_authors <- ncd %>%
   mutate(Author = fct_lump(fct_explicit_na(Author), n =topn))%>%
   count(Author) %>%
   top_n(topn) 


prop_topA_byAY <- ncd %>%
   filter(Author %in% top_authors$Author) %>%
   group_by(Author, Year) %>%
   summarise(count = n()) %>%
   mutate(prop = count / sum(count)) %>%
   group_by(Year) %>%
   mutate(yrprop = count / sum(count)) %>%
   mutate(yrcount = sum(count)) %>%
   arrange(Year)

   
ggplot(prop_topA_byAY, aes(x=Year, y=count, fill=Author)) + 
   geom_bar(stat="identity", colour="white") +
   ggtitle(paste0("Top ",topn," Authors by Year: Count"))  

ggplot(prop_topA_byAY, aes(x=Year, y=yrprop, fill=Author)) + 
   geom_bar(stat="identity", colour="white")  +
   ylab("Proportion") +
   ggtitle(paste0("Top ",topn," Authors by Year: Proportion of Count")) +
   geom_text(aes(label=yrcount,x=Year,y=1.01), vjust=-0.3)
```

````{r, echo=F, warning=F, message=F}
# library(gapminder)
# ccountries <- gapminder::country_colors
# ccountries <- as.data.frame(ccountries)
# ccontinents <- gapminder::continent_colors
# ccontinents <- as.data.frame(ccontinents)
# 
# write.csv(ccountries, "gapminder_countries.csv", row.names=T)
# write.csv(ccontinents, "gapminder_ccontinents.csv", row.names=T)
# 
# ccolours <- read_csv("gapminder_CC.csv")
# 
# ncd_c <- left_join(ncd, ccolours, by ="Country")
# 
# col5_vec <- I(ccolours$Colour5)
# names(col5_vec) <- ccolours$Country

```


### Top 20 Countries
```{r, echo=F, warning=F, message=F}

topn <- 20

#fct_lump to get topn (and lump all others) 
top_countries <- ncd %>%
   mutate(Country = fct_lump(fct_explicit_na(Country), n = topn))%>%
   count(Country) %>%
   top_n(topn) 

#need this to match up 'other' created by fct_lump above
top_ncd <- ncd %>%
   mutate(Country = fct_lump(fct_explicit_na(Country), n = topn))

prop_topC_byCY <- top_ncd %>%
   filter(Country %in% top_countries$Country) %>%
   group_by(Country, Year) %>%
   summarise(count = n()) %>%
   mutate(prop = count / sum(count)) %>%
   group_by(Year) %>%
   mutate(yrprop = count / sum(count)) %>%
   mutate(yrcount = sum(count)) %>%
   arrange(Year)

prop_topC_byCY <- left_join(prop_topC_byCY, ccolours, by ="Country")
   
ggplot(prop_topC_byCY, aes(x=Year, y=count, fill=Country)) + 
   geom_bar(stat="identity", colour="white") +
   ggtitle(paste0("Top ",topn," Countries by Year: Count")) +
   scale_fill_manual(values=col5_vec)


ggplot(prop_topC_byCY, aes(x=Year, y=yrprop, fill=Country)) + 
   geom_bar(stat="identity", colour="white")  +
   ylab("Proportion")  +
   ggtitle(paste0("Top ",topn," Countries by Year: Proportion of Count")) +
   geom_text(aes(label=yrcount,x=Year,y=1.01), vjust=-0.3) +
   scale_fill_manual(values=col5_vec)
```

### Top 10 Countries
```{r, echo=F, warning=F, message=F}

topn <- 10

#fct_lump to get topn (and lump all others) 
top_countries <- ncd %>%
   mutate(Country = fct_lump(fct_explicit_na(Country), n = topn))%>%
   count(Country) %>%
   top_n(topn, Country) 

#need this to match up 'other' created by fct_lump above
top_ncd <- ncd %>%
   mutate(Country = fct_lump(fct_explicit_na(Country), n = topn))

#calc proportions
prop_topC_byCY <- top_ncd %>%
   filter(Country %in% top_countries$Country) %>%
   group_by(Country, Year) %>%
   summarise(count = n()) %>%
   mutate(prop = count / sum(count)) %>%
   group_by(Year) %>%
   mutate(yrprop = count / sum(count)) %>%
   mutate(yrcount = sum(count)) %>%
   arrange(Year)

   
ggplot(prop_topC_byCY, aes(x=Year, y=count, fill=Country)) + 
   geom_bar(stat="identity", colour="white")  +
   ggtitle(paste0("Top ",topn," Countries by Year: Count"))  +
   scale_fill_manual(values=top10_vec)

ggplot(prop_topC_byCY, aes(x=Year, y=yrprop, fill=Country)) + 
   geom_bar(stat="identity", colour="white")  +
   ylab("Proportion")  +
   ggtitle(paste0("Top ",topn," Countries by Year: Proportion of Count")) +
   geom_text(aes(label=yrcount,x=Year,y=1.01), vjust=-0.3) +
   scale_fill_manual(values=top10_vec)


```

### Continents
```{r, echo=F, warning=F, message=F}

freq_CY <- ncd %>% group_by(Continent, Year) %>%
   summarise(count = n()) %>%
   mutate(prop = count / sum(count)) %>%
   group_by(Year) %>%
   mutate(yrprop = count / sum(count)) %>%
   mutate(yrcount = sum(count)) %>%
   arrange(Year)

ggplot(freq_CY, aes(x=Year, y=count, fill=Continent)) + 
   geom_bar(stat="identity", colour="white") +
   ggtitle("Author Continent by Year: Count") +
   scale_fill_manual(values=con6_vec)

ggplot(freq_CY, aes(x=Year, y=yrprop, fill=Continent)) + 
   geom_bar(stat="identity", colour="white") +
   ylab("Proportion")+
   ggtitle("Author Continent by Year: Proportion of Count") +
   geom_text(aes(label=yrcount,x=Year,y=1.01), vjust=-0.3)  +
   scale_fill_manual(values=con6_vec)

```

### Institution Type
```{r, echo=F, warning=F, message=F}

freq_ITY <- ncd %>% group_by(`Institution Type`, Year) %>%
   summarise(count = n()) %>%
   mutate(prop = count / sum(count)) %>%
   group_by(Year) %>%
   mutate(yrprop = count / sum(count)) %>%
   mutate(yrcount = sum(count)) %>%
   arrange(Year)

ggplot(freq_ITY, aes(x=Year, y=count, fill=`Institution Type`)) + 
   geom_bar(stat="identity", colour="white") +
   ggtitle("Author Institution Type by Year: Count")  

ggplot(freq_ITY, aes(x=Year, y=yrprop, fill=`Institution Type`)) + 
   geom_bar(stat="identity", colour="white")  +
   ylab("Proportion")  +
   ggtitle("Author Inst. Type by Year: Proportion of Count") +
   geom_text(aes(label=yrcount,x=Year,y=1.01), vjust=-0.3)


```


